---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
  namespace: pks-argocd-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
        - name: demo-server
          image: "ghcr.io/poolc/pks-argocd-demo:7a8db19a9afa1b5cc1d51da00d25933849d0f7af"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
