---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
        - name: demo-server
          image: "ghcr.io/poolc/pks-argocd-demo:14dbe44dce316e11198e2880e96555513da0dd39"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
